name: Build Plugin ZIP

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Plugin Directory
        run: mkdir -p update-service-log

      - name: Move Files to Plugin Directory
        run: mv * update-service-log/

      - name: Zip Plugin
        run: zip -r update-service-log.zip update-service-log

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: update-service-log.zip
