name: WordPress Plugin Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create and Upload Plugin Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Create Plugin ZIP
        run: |
          mkdir -p build
          zip -r build/update-service-log.zip . -x ".git*" ".github*" "build/*"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/update-service-log.zip
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use Personal Access Token
